import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainPageBorder from "./_components/MainPageBorder";
import NavigationMenu from "./_components/NavigationMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-slate-800 text-slate-200`}>
        <MainPageBorder>
          <NavigationMenu />
          {children}
        </MainPageBorder>
      </body>
    </html>
  );
}
